#!/bin/bash
set -eu
NAME="dzenotify"
GENERIC_FONT="-misc-fixed-*-*-*-*-20-*-*-*-*-*-*-*"
Y_MARGIN=30

if [ "$#" -ne "2" ]
then
    echo "Usage: $NAME <summary> <body>"
    exit 1
fi

summary="$1"
body="$2"

notification="$summary: $body"

width=$(textwidth "$GENERIC_FONT" "$notification")
half_margin=$(expr $Y_MARGIN '/' 2)
height=$(expr $Y_MARGIN '+' $half_margin)
x_margin=$(expr $half_margin '+' $width)
geometry="${width}x${height}-${x_margin}+${Y_MARGIN}"

echo "^fg(green)$summary: ^fg(white)$body" | nohup dzen2 -p 5 -geometry $geometry -xs 1 &>/dev/null &
